spring.application.name=localstorage

# =========================
# DATABASE
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/local_storage}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =========================
# FILE UPLOAD
# =========================
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# =========================
# AWS S3
# =========================
aws.s3.bucket=${AWS_S3_BUCKET}
aws.s3.region=${AWS_S3_REGION}
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}

# =========================
# CIRCUIT BREAKER
# =========================
resilience4j.circuitbreaker.instances.s3CircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.s3CircuitBreaker.slidingWindowSize=5
resilience4j.circuitbreaker.instances.s3CircuitBreaker.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.s3CircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.s3CircuitBreaker.waitDurationInOpenState=15s
resilience4j.circuitbreaker.instances.s3CircuitBreaker.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.s3CircuitBreaker.recordExceptions=java.lang.Exception

# =========================
# LOGGING
# =========================
logging.level.io.github.resilience4j=DEBUG
logging.level.io.github.resilience4j.circuitbreaker=DEBUG

management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always
